### ISSUE TITLE
application launcher

### ISSUE THREAD

**Issue by EliaHKM** [linkfrg/dotfiles#1]
Hi,
Thank you for sharing your awesome config
I've one problem the application launcher is blank
and doesn't show any application when I type 
on the search filed I've installed everything in 
the wiki and placed the configs too 

when I run apps.py in the terminal it gives this:
`Traceback (most recent call last):
  File "/home/darkeye/.config/eww/scripts/apps.py", line 127, in <module>
    entries = get_desktop_entries()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/darkeye/.config/eww/scripts/apps.py", line 31, in get_desktop_entries
    parser.read(file_path)
  File "/usr/lib/python3.11/configparser.py", line 713, in read
    self._read(fp, filename)
  File "/usr/lib/python3.11/configparser.py", line 1112, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/share/applications/reboot-to-uefi.desktop' [line  6]: option 'comment' in section 'Desktop Entry' already exists`

so could you help me please?

**Comment by linkfrg** [comment]
It looks like you have created a custom desktop file called `reboot-to-uefi.desktop` which have a duplicated option `comment,` try remove this duplicated option or remove this desktop file(if you don't need it)

**Comment by EliaHKM** [comment]
thanks the launcher now is working
but the search is not and I don't know 
how to pin the apps 
thanks again

**Comment by linkfrg** [comment]
to pin apps right click on them(if you on old version middle click). Search should work on last commit. But if you don't want to update replace `scripts/apps.py --query '{}'` by `scripts/apps.py --query '{}' &` in `.config/eww/modules/launcher.yuck`
