### ISSUE TITLE
Some features arent working on [Artix] (App launcher,check volume,toggle center, etc)

### ISSUE THREAD

**Issue by ahmadjerjawi** [linkfrg/dotfiles#10]
Hey there, I've run into a snag with the dotfiles on Artix, and I'm hoping for some assistance. I've tested this issue twice—once with a minimal install and another with KDE Plasma—but it's persisting.

Details:
- Dotfiles seem to play nice with power menu, kitty, Thunar color picker, wallpaper changer, and generator.
- However, the app launcher, toggle center, language changer, and a few others aren't cooperating.
- When running the corresponding shell files, I'm not seeing any visual changes, but suddenly I can't type, hinting that something's going on in the background.
- Tried capturing errors through logging and text file output, but no luck.
- Notably, this doesn't seem like an Artix-specific problem. I've used different dotfiles before, and most worked, or at least flagged dependencies related to systemd when installing. 

Environment:
- OS: Artix
- Installations: Minimal and KDE Plasma
If you can't help me this is OK I am still not expert on eww so I can't get the hang of it and if any details needed  I will be here

**Comment by linkfrg** [comment]
Install non git version of hyprland, see #3

**Comment by ahmadjerjawi** [comment]
Oh yeah thx I feel stupid right now
