### ISSUE TITLE
I just want to have a few themes, not change it based on the wallpaper

### ISSUE THREAD

**Issue by CRAG666** [linkfrg/dotfiles#14]
This is truly incredible, honestly the idea of ​​changing the theme according to the image is excellent. However many times this looks horrible in the terminal. That's why I would like to just have a color scheme, for example catppuccin, since I have spent a lot of time making my system look integrated, do you have any ideas how I can do that?

**Comment by CRAG666** [comment]
I also take the opportunity to ask what configuration you have in qt5ct, since until now I have not been able to get the gradience themes to work in the qt applications

**Comment by linkfrg** [comment]
You can change the colors to whatever you want in ~/.config/eww/scripts/colors. Be careful, they will be overwritten at next monet colors generation.

**Comment by linkfrg** [comment]
I don't use qt apps and don't have configuration for qt5ct

**Comment by CRAG666** [comment]
how to change hight of bar. It is very thick @linkfrg thanks 
![2024-01-07T14:57:29,282813718-06:00](https://github.com/linkfrg/dotfiles/assets/34254373/4c63d4a7-c388-47d0-8e05-895a9db36192)

**Comment by linkfrg** [comment]
You need to decrease values of `margin`, `padding`, `font-size`, `min-height` in bar widgets scss.
You can find them in `~/.config/eww/scss`

**Comment by CRAG666** [comment]
I still don't understand why it looks so big when my monitor is 1080 and the scale I'm using is 1
![2024-01-07T17:44:08,972124423-06:00](https://github.com/linkfrg/dotfiles/assets/34254373/761860e9-5735-4a27-95fe-ed88c627f370)

**Comment by CRAG666** [comment]
@linkfrg thanks
