### ISSUE TITLE
please add battery icon in systray 

### ISSUE THREAD

**Issue by vs66388** [linkfrg/dotfiles#2]

**Comment by linkfrg** [comment]
I don’t understand a little, the tray is already there and the battery icon will be there. You may need to open a tray window(press button with arrow in bar) and restart cbatticon or something like this

**Comment by vs66388** [comment]
I mean I've got a laptop and there is no battery indicator in bar if possible can you add it I mean in

**Comment by vs66388** [comment]
![Screenshot_2023-11-03-21-16-01-57_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/linkfrg/dotfiles/assets/126272029/24cba24a-08f0-47b9-a719-f4e259eea140)

**Comment by linkfrg** [comment]
I don't have laptop so i can't test it, You can add it yourself in `modules/indicator.yuck`

**Comment by vs66388** [comment]
Can you guide how to I'll do it then I am a newbe in this kind of stuff if you explain keeping that in mind I'll be much more thankfull

**Comment by A31Nesta** [comment]
I added the battery indicator for my laptop. I edited `indicator.yuck` inside the modules folder.

At the bottom of the file I added:
~~~
(defwidget battery_icon []
    (state_icon :condition true
                :text {EWW_BATTERY.BAT1.capacity > 90 ? " " : EWW_BATTERY.BAT1.capacity > 75 ? " " : EWW_BATTERY.BAT1.capacity > 50 ? " " : EWW_BATTERY.BAT1.capacity > 25 ? " " : " "}
    )
)
~~~

and then at the top of the file I added my `battery_icon` to the `indicator` like this:
~~~
(defwidget indicator []
    (button :onclick "scripts/toggle_control_center.sh" :class "indicator"
        (box :orientation "h" :space-evenly false
            (recorder_icon)
            (network_icon)
            (do-not-disturb_icon)
            (theme_icon)
            (volume_icon)
            (battery_icon)
            (clock)
        )
    )
)
~~~

**Comment by vs66388** [comment]
Thank you bro you are a life saver

**Comment by linkfrg** [comment]
if battery icon is still not showing, replace `BAT0` in `(battery_icon)` widget in `indicator.yuck` by battery name from `eww get EWW_BATTERY`

**Comment by vs66388** [comment]
It is visible thanks
