### ISSUE TITLE
Icons misplaced in eww bar + automatically focus on search bar

### ISSUE THREAD

**Issue by qbnil** [linkfrg/dotfiles#20]
1) ![2024-04-18T14:16:29,787400418+03:00](https://github.com/linkfrg/dotfiles/assets/130576530/8ad1fcb2-cd75-4ed5-9c59-b1dcf19dee6c)
![2024-04-18T14:17:06,111380006+03:00](https://github.com/linkfrg/dotfiles/assets/130576530/5c008dfa-b9e1-4203-8ece-5ec702bb7513)
There is an issue that i have, the very first time i booted into hyprland, the icons were looking just alright, but now all of them are kinda in the wrong place, how do i position them normally?
2) Is there any way to automatically put the cursor in the search bar for searching applications and not do that manually, thx in advance...

**Comment by linkfrg** [comment]
1. remove all nerd fonts except `ttf-jetbrains-mono` and `ttf-nerd-fonts-symbols`, to list all fonts use `pacman -Q | grep ttf`
2. i think no, eww have no this feature

**Comment by qbnil** [comment]
Does that mean there is no way i can install some other font anymore?

**Comment by linkfrg** [comment]
there is no way you can install other nerd font except `ttf-nerd-fonts-symbols`

**Comment by qbnil** [comment]
Btw, i lost your wallpaper by changin it to another one, where do you store it, the one with the flowers?

**Comment by linkfrg** [comment]
https://github.com/linkfrg/wallpapers/blob/main/nature/purple.jpg

**Comment by qbnil** [comment]
Thx, btw, i managed to fix the icons problem by just replacing yours with the emojis and it looks pretty fun 
![image](https://github.com/linkfrg/dotfiles/assets/130576530/ec456c16-6342-4c15-be47-277484f2aa7d)
![image](https://github.com/linkfrg/dotfiles/assets/130576530/ecbd95a3-bcec-46f1-8fde-99de39cef72b)

**Comment by qbnil** [comment]
The last thing i wanted to ask you was about pinnning the apps to the taskbar, the hotkey seems to not work..

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/0c46b218-6fee-4838-aa9a-b98658490c95)
I also noticed that the way the spotify song is begin displayed in your preview, i only see this: 
![image](https://github.com/linkfrg/dotfiles/assets/130576530/dbaa47ce-3399-47b3-ae55-418eab6d9d5d)
without any pic:(

**Comment by linkfrg** [comment]
to pin app in launcher right click on it

**Comment by linkfrg** [comment]
hmmm I can't reproduce the problem with spotify

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/5735cef0-77eb-4cf1-be84-e3169cc536fe)
I mean pinning like this, just making sure you got it right. I right click on the app in launcher here: 
![image](https://github.com/linkfrg/dotfiles/assets/130576530/8b0e6931-2a6e-44db-98db-e858ed5caf61)
but can't pin anything, it just opens the app

**Comment by qbnil** [comment]
Fixed the durition bar problem by installing bc manually from pacman repos, you better include it in your wiki, still figuring out how to make the pic appear

**Comment by qbnil** [comment]
Может на русском проще будет объяснить,  я так понимаю, что mpris.sh это конфиг как раз для этого, но прикол в том, что с картинкой я там ничего не увидел, исходя из того, что у меня там сейчас: 
#!/bin/bash

playerctl metadata -F -f '{{playerName}} {{title}} {{artist}} {{mpris:artUrl}} {{status}} {{mpris:length}}' | while read -r line; do
    name=$(playerctl metadata -f "{{playerName}}")
    title=$(playerctl metadata -f "{{title}}")
    artist=$(playerctl metadata -f "{{artist}}")
    artUrl=$(playerctl metadata -f "{{mpris:artUrl}}")
    status=$(playerctl metadata -f "{{status}}")
    length=$(playerctl metadata -f "{{mpris:length}}")
    if [[ $length != "" ]]; then
        length=$(($length / 1000000))
        length=$(echo "($length + 0.5) / 1" | bc)
    fi
    lengthStr=$(playerctl metadata -f "{{duration(mpris:length)}}")

    JSON_STRING=$( jq -n \
                --arg name "$name" \
                --arg title "$title" \
                --arg artist "$artist" \
                --arg artUrl "$artUrl" \
                --arg status "$status" \
                --arg length "$length" \
                --arg lengthStr "$lengthStr" \
                '{name: $name, title: $title, artist: $artist, artUrl: $artUrl, status: $status, length: $length, lengthStr: $lengthStr}' )
    echo $JSON_STRING
done

**Comment by qbnil** [comment]
Хотя artUrl это, наверное и есть то, что нужно

**Comment by qbnil** [comment]
да, с нуля поставил и накатил потом твои конфиги

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/d0dde6b1-2259-4cba-a863-89d93b4c082d)
пофиксил так пока
пока смотрел файлик mpris.sh заметил, что все валится на строках, где mpris упомянается, length отрабатывает, потому что потом вручную рассчитывается с помощью bc

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/a2a3dcb6-d9e0-4cb4-8567-2af7654b66e6)

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/352befff-8ae3-435d-991f-10fada1d7e36)
Однако...

**Comment by qbnil** [comment]
что-то все-таки есть, может надо ребутнуть, сек

**Comment by qbnil** [comment]
приложения закрепить получилось, а каринка так и не появляется, странно, даже ссылка активная с картинкой, надо в выводе смотреть что как. Жалко, что еще не работает pin по хоткею $mainmod + h у тебя в конфиге есть. И как открепить можно кстати?

**Comment by linkfrg** [comment]
хоткея $mainmod + h нету, и закрепление приложений по бинду я не добавлял. Чтобы открепить надо в лаунчере где Pinned нажать пкм

**Comment by qbnil** [comment]
![image](https://github.com/linkfrg/dotfiles/assets/130576530/1f7ac3ad-cef2-4756-8709-826b9ebc0da5)
а это для чего?

**Comment by linkfrg** [comment]
это чтобы закрепить окно, а не приложение

**Comment by qbnil** [comment]
а, это с окнами просто связано, пон, надо только разобраться каким образом оно закрепляет

**Comment by qbnil** [comment]
> это чтобы закрепить окно, а не приложение

пон, пон

**Comment by qbnil** [comment]
https://github.com/husseinhareb/hyprland-eww/blob/main/eww/dashboard/scripts/spotify/spotify-artwork.sh
нашел интересный сорс, тут похожее на твое делают, с картинкой, можно попробовать

**Comment by qbnil** [comment]
разве так будет работать, просто подставляя http в --arg ? как строку..

**Comment by linkfrg** [comment]
> https://github.com/husseinhareb/hyprland-eww/blob/main/eww/dashboard/scripts/spotify/spotify-artwork.sh нашел интересный сорс, тут похожее на твое делают, с картинкой, можно попробовать

я сейчас eww не пользуюсь и работаю над другим проектом, так что фиксить я что-то вряд-ли буду

**Comment by qbnil** [comment]
понял, если сделаю что-то, мр кину..

**Comment by qbnil** [comment]
ну вот, ахах, пофиксил, давай мр кину?

**Comment by linkfrg** [comment]
у меня уже открыт какой-то пулл реквест #16, давай я его сейчас смержу и ты на новой версии уже сделаешь фикс

**Comment by qbnil** [comment]
окей, дай знать, когда

**Comment by qbnil** [comment]
я потому что уже твой репо клонировал к себе

**Comment by qbnil** [comment]
мерж тогда и я на новые изменения долью
