### ISSUE TITLE
Ignis Init Error: Bad Marshal Data

### ISSUE THREAD

**Issue by cchinchole** [linkfrg/dotfiles#25]
When using the dotfiles, I am receiving a bad marshal data error ONLY when using this configuration. Using the example bar configuration, the application launches correctly. I confirmed the versions for pillow, materialyoucolor, and jinja meet the spec listed as per requirements.txt. Any ideas if this could be an issue on my end?

Edited: Moved the log to an attachment as github was striking text.

[ignis_log.txt](https://github.com/user-attachments/files/17217629/ignis_log.txt)

**Comment by linkfrg** [comment]
Never saw this error. Try to clean all ``__pycache__`` directories and ``.pyc`` files inside dotfiles dir

**Comment by cchinchole** [comment]
Interesting, I had never seen this error before either, but doing an entire delete of all .pyc files did the trick. Likely a local issue with something corrupted, but if anyone else experiences this: find / -name '*.pyc' -delete
Thanks for the help!
