### ISSUE TITLE
See video

### ISSUE THREAD

**Issue by Dreuzz** [linkfrg/dotfiles#26]
https://github.com/user-attachments/assets/f559265b-1480-4cd1-a3b7-8fdff0d5a40c

- Material design doesnt work on some places (bar, logout)
- white overlay when in control center
- dark mode doesnt work

**Comment by linkfrg** [comment]
do you have modified ``gtk.css``? in ``~/.config/gtk-4.0``

**Comment by Dreuzz** [comment]
yeah I did, but I reapplied all the files again and it still didnt work

**Comment by linkfrg** [comment]
styles defined in ``gtk.css`` will override styles provided by gtk applications, including Ignis. Try completely removing it

**Comment by Dreuzz** [comment]
I fixed it, rewrote some parts of the code and it works fine. Just have to implement my Wallpaper script and mostly done. Also is it okay if I post my version of ignis which I forked from you on r/unixporn?

**Comment by linkfrg** [comment]
> Also is it okay if I post my version of ignis which I forked from you on r/unixporn?

Probably yes, but people will probably have problems with the installation. And if you need any additional functionality or fix in Ignis, you can always open a pull request

**Comment by Dreuzz** [comment]
I prob wont share my dots since I dont know how to configure them but will try to make it work if I do so.

**Comment by linkfrg** [comment]
> Also is it okay if I post my version of ignis which I forked from you on r/unixporn?

If it's not a secret, what changes did you make?

I saw your post on r/unixporn and many people asked you for dotfiles, and I think you should post them despite possible installation problems, don't miss the chance to get a couple of extra stars on the repository

**Comment by Dreuzz** [comment]
> > Also is it okay if I post my version of ignis which I forked from you on r/unixporn?
> 
> If it's not a secret, what changes did you make?
> 
> I saw your post on r/unixporn and many people asked you for dotfiles, and I think you should post them despite possible installation problems, don't miss the chance to get a couple of extra stars on the repository

https://github.com/Dreuzz/dotfiles
