### ISSUE TITLE
Request to Add Battery Icon to Bar

### ISSUE THREAD

**Issue by Munseer-am** [linkfrg/dotfiles#27]
Hello,

I recently installed your Arch rice, and I noticed that the bar does not have a battery icon to indicate the charge level. 

Could you please consider implementing a battery icon in the bar?

Thank you!

**Comment by MNkoder** [comment]
hey, this was already requested by me and a few others, linkfrg said he doesn't have a device with battery to test it as he is a pc only user, so either someone has to make the battery service and widget and add a commit to ignis (i guess) or lets hope linkfrg can do it anyway

**Comment by linkfrg** [comment]
I can make a pull request with the battery service. Only need testing

**Comment by MNkoder** [comment]
> I can make a pull request for Ignis with the battery service. Only need testing

i can help you with that

**Comment by Munseer-am** [comment]
> > I can make a pull request for Ignis with the battery service. Only need testing
> 
> i can help you with that

Thanks for the info! I'll keep an eye on the updates.

**Comment by Munseer-am** [comment]
Thanks for the info! I didn't check the other PRs before making the suggestion, my bad. I'll keep an eye on the updates!

**Comment by linkfrg** [comment]
I created [Pull Request](https://github.com/linkfrg/ignis/pull/10)

**Comment by linkfrg** [comment]
linkfrg/ignis@#10 merged
ad05692 adds battery widget.

Closing
