### ISSUE TITLE
Bluetooth

### ISSUE THREAD

**Issue by xrhstosmour** [linkfrg/dotfiles#28]
Is there any documentation on how to implement a bluetooth module?

**Comment by linkfrg** [comment]
[Creating Service](https://linkfrg.github.io/ignis/latest/dev/creating_service.html). In general, it’s better to create a separate service in Ignis, but again, i don't have bluetooth  adapter

**Comment by xrhstosmour** [comment]
I might open a PR on the `ignis` repository if I find the time. Keep up the great work on both projects!
