### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by zhuchops** [linkfrg/dotfiles#29]
I have installed your dotfiles. but i havent ignis_LAUNCHER and POWERMENU. i dont have bar at the top when i am trying to init ignis in terminal it exiting with error. if i try to use sudo it says this 
`sudo ignis init                                                                                           ─╯
Traceback (most recent call last):
  File "/usr/bin/ignis", line 5, in <module>
    main()
  File "/usr/lib/python3.12/site-packages/ignis/main.py", line 12, in main
    cli()
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ignis/cli.py", line 65, in init
    client = IgnisClient()
             ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ignis/client.py", line 36, in __init__
    self.__dbus = DBusProxy(
                  ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ignis/dbus.py", line 264, in __init__
    self._proxy = Gio.DBusProxy.new_for_bus_sync(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-io-error-quark: Error receiving data: Connection reset by peer (44)
`
do i have to do smth else after installation. ( i tried rebooting )

**Comment by linkfrg** [comment]
1. Do not launch Ignis as sudo!!!
2. Launch Ignis as normal user and send the logs (``~/.ignis/ignis.log``) or the output from the terminal.

**Comment by zhuchops** [comment]
thats what i see in terminal when i do "ignis init"
`2024-10-04 20:03:59 [INFO] Using configuration file: /home/zhuchok/.config/ignis/config.py
2024-10-04 20:04:00 [INFO] Applied css: /home/zhuchok/.config/ignis/style.scss

(python3:6841): Gdk-WARNING **: 20:04:00.120: vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED) (-3)

(python3:6841): Gdk-WARNING **: 20:04:00.144: vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED) (-3)
2024-10-04 20:04:00 [INFO] Ready.
Gdk-Message: 20:04:00.150: Error 12 (Cannot allocate memory) dispatching to Wayland display.`

**Comment by zhuchops** [comment]
and this is stored in (~/.ignis/ignis.log)
`ignis init                                                ─╯
2024-10-04 20:03:59 [INFO] Using configuration file: /home/zhuchok/.config/ignis/config.py
2024-10-04 20:04:00 [INFO] Applied css: /home/zhuchok/.config/ignis/style.scss

(python3:6841): Gdk-WARNING **: 20:04:00.120: vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED) (-3)

(python3:6841): Gdk-WARNING **: 20:04:00.144: vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): Initialization of an object could not be completed for implementation-specific reasons. (VK_ERROR_INITIALIZATION_FAILED) (-3)
2024-10-04 20:04:00 [INFO] Ready.
Gdk-Message: 20:04:00.150: Error 12 (Cannot allocate memory) dispatching to Wayland display.`

**Comment by linkfrg** [comment]
You have problems with the Vulkan drivers. Are you using AMD? If yes, as far as I know, you need to additionally install the Vulkan drivers

**Comment by zhuchops** [comment]
oh, okey, i`ll try and then write down here

**Comment by zhuchops** [comment]
thanks

**Comment by zhuchops** [comment]
![image](https://github.com/user-attachments/assets/eb7a553a-461f-4694-b947-fda3eeece4f6)
so, i had this one before, i think the problem not in drivers

**Comment by linkfrg** [comment]
According to the errors, the problem is related to Gdk and Vulkan, not specifically to Ignis

**Comment by zhuchops** [comment]
ok, i`ll try smth do and may be smth will happened)

**Comment by tyrypyrking** [comment]
As the error says PhysicalDeviceSurfaceCapabilities, it can't get Surface capabilities for your specific device. Do you have any issues with other vulkan applications on your system? Does your device support vulkan at all?

**Comment by zhuchops** [comment]
sorry for not writing here, i just have given up, i`ll close this issue
