### ISSUE TITLE
[BUG] cannot start blueman-applet with hypr config 

### ISSUE THREAD

**Issue by tyrypyrking** [linkfrg/dotfiles#37]
Adding
```
exec-once = blueman-applet&
```
causes it to always fails (speculation: as ignis init doesn't seem to be initialized yet to accept the event?). Adding sleep fixes the issue, but that's still a concern.

```
exec-once = sleep 4 && blueman-applet& 
```

**Comment by linkfrg** [comment]
It’s logical that if you launch blueman-applet before Ignis is initialized, it will not start because there is no bar and system tray. I don't see an issue

**Comment by tyrypyrking** [comment]
Because ignis init doesn't finish the init, I can't do something like ignis init && blueman-applet too. So it returns success, but isn't ready to handle stuff.

**Comment by linkfrg** [comment]
Again, i don't see the issue. Hyprland launch commands defined in ``exec-once``s in background,  so they start almost instantly, it doesn’t wait until Ignis starts, and shoudn't, that’s normal. Just use ``sleep 4 && blueman-applet&``
