### ISSUE TITLE
[FEATURE] Vpn menu

### ISSUE THREAD

**Issue by tyrypyrking** [linkfrg/dotfiles#38]
Would be pretty cool to have a styled menu for VPN connections, besides wifi/ethernet.

**Comment by linkfrg** [comment]
1. Need support for VPN connections in Ignis (maybe part of the Network Service or a separated service)
2. I'm very unlikely to do this right now, unless a lot of people need it (let's just say that if there are 15 reactions under this comment, then I will do it)

**Comment by u1dm** [comment]
**If you've set up your VPN using WireGuard or similar tools, you can customize your own menu. For instance, you can take an existing WiFi menu and build your custom VPN menu from there.**

**Comment by tyrypyrking** [comment]
Alright, then I'll take it as a sign to do it on my own. I'll make a PR to ignis once it's ready, should be straight forward to implement.

**Comment by tyrypyrking** [comment]
Added PRs to both ignis and this dotfiles repo:
https://github.com/linkfrg/ignis/pull/29
https://github.com/linkfrg/dotfiles/pull/40

**Comment by tyrypyrking** [comment]
https://github.com/user-attachments/assets/8c10d611-d7c0-4c4b-8719-254930af30be

Here's how it looks. That jittery close after connection is established is another issue that I'm working on.

**Comment by tyrypyrking** [comment]
#40  is merged, closing the issue.
