### ISSUE TITLE
BUG: Unresponsive UI after laptop lid open

### ISSUE THREAD

**Issue by tyrypyrking** [linkfrg/dotfiles#42]
Had it twice so far, should be tied to GPU going to sleep causing update loop to break. I'll look into it.

**Comment by linkfrg** [comment]
This is a GPU related issue. If you use Nvidia, see this: https://wiki.archlinux.org/title/NVIDIA/Tips_and_tricks#Preserve_video_memory_after_suspend

**Comment by tyrypyrking** [comment]
Thanks, I'll check it out.
Only ignis is freezing though, I'd expect it to fail or restart, but not to be stuck.

**Comment by tyrypyrking** [comment]
Been running the fix for a few days, doesn't seem to appear anymore.
