### ISSUE TITLE
BUG:  No binding for ignis settings  I cannot access the appearance settings, etc 

### ISSUE THREAD

**Issue by dwilliam62** [linkfrg/dotfiles#43]
I installed the main branch first. 

 There is no binding for the appearance app in your dotfiles.  Just two references for the Power Menu 

I can run the other ignus apps w/o issue 

![image](https://github.com/user-attachments/assets/4ecd2ac3-a434-4d5c-8275-2512d8262042)

But the settings one does not work.  See screenshot 

I then tried the dev branch and that did not resolve it.  

There isn't any documentation on adding apps to the bar.  Unless that's done via the Appearance app? 

 Thanks

**Comment by linkfrg** [comment]
1. There is no dev branch, i deleted it. Where did you get it??? Anyway, don't use it.
2. You can launch settings only through control center, doing it through CLI is not supported.
3. To add an app to the bar, open launcher, search for it, right click and select "Pin"

**Comment by linkfrg** [comment]
> There isn't any documentation on adding apps to the bar. Unless that's done via the Appearance app?

I think it's intuitive, plus I showed it in my post on r/unixporn.

**Comment by dwilliam62** [comment]
How do I start the control center?    No binding and using the launcher doesn't come up with it either

**Comment by dwilliam62** [comment]
Also I didn't see this on r/unixporn   It was posted on a  discord server

**Comment by linkfrg** [comment]
What post? The last time I posted my rice on Discord was a year ago.

See the post on [r/unixporn](https://www.reddit.com/r/unixporn/s/kRUUjruskV)

**Comment by dwilliam62** [comment]
thank you.   

Re: Discord I did not say you posted it.  I said 'it' was posted to a discord server by someone else.   But that's all they posted was the github page.  

re: ddv.  Your installation page mentioned the dev branch 

![image](https://github.com/user-attachments/assets/6110e5a5-3c45-43a4-a1d7-ff8ba76ad988)

**Comment by linkfrg** [comment]
> re: ddv. Your installation page mentioned the dev branch\n\n

Ohh, i forgot to remove this
