### ISSUE TITLE
[Bug] Screenshot preview not functioning

### ISSUE THREAD

**Issue by jonahbrawley** [linkfrg/dotfiles#45]
Potentially could be an ignis bug, but when taking a screengrab on my system the image preview is just black. Maybe a dependency missing on my system?

![image](https://github.com/user-attachments/assets/9e385a7c-ae2d-40d0-bcaa-3685e700d2b6)

Notification center:
![image](https://github.com/user-attachments/assets/08ca749f-6a01-4a63-95a0-e0690d94a8a5)

**Comment by linkfrg** [comment]
Are you doing screenshot of area or full screen?

**Comment by jonahbrawley** [comment]
Screenshot of area, but the same behavior happens with fullscreen

**Comment by linkfrg** [comment]
Are the screenshots themselves saved in ``~/Pictures`` normally?
Also please attach the ``ignis.log`` (``~/.ignis/ignis.log``) or the output from the terminal  where Ignis is running

**Comment by jonahbrawley** [comment]
Sorry, wish I had more helpful info to share. Maybe it has something to do with the notification daemon dunst?

**Comment by linkfrg** [comment]
> Sorry, wish I had more helpful info to share. Maybe it has something to do with the notification daemon dunst?

Maybe. It is advisable to uninstall it

**Comment by linkfrg** [comment]
Can you open a one colored application (like xterm) (with no black color) in fullscreen and take a screenshot?

**Comment by jonahbrawley** [comment]
Just tried opening Xterm in fullscreen with F11, took a screenshot and still no preview

**Comment by jonahbrawley** [comment]
Tried switching from grimshot to hyprshot, and preview works there. This should work just fine for my purposes. Will opt to close this and if I find a way to make grimshot work, I will update here
