### ISSUE TITLE
Ignis freezes after waking from suspend

### ISSUE THREAD

**Issue by jonahbrawley** [linkfrg/dotfiles#46]
After waking from suspend (from power menu), ignis freezes and becomes unresponsive. Sometimes it will recover after about 30 seconds and start working again, other times it won't recover and I will have to reload with `ignis reload` or killall and reinitialize.

Note that this issue doesn't occur when locking with Hyprlock and unlocking, but only after suspending and waking up. No logs are given when running in terminal and doing this

**Comment by jonahbrawley** [comment]
Closed as this should be made under ignis' repo

**Comment by jonahbrawley** [comment]
Actually moving to reopen since I cannot be sure if this is caused by ignis or dotfiles configuration.

**Comment by linkfrg** [comment]
https://linkfrg.github.io/ignis/stable/user/faq.html#render-issues-or-unresponsive-ui-after-wake-up-from-suspend
