### ISSUE TITLE
Icons in ignis broken

### ISSUE THREAD

**Issue by KnoyanMitsu** [linkfrg/dotfiles#47]
hmm guys how i change icons on control panel i try using exec-once = gsettings set org.gnome.desktop.interface icon-theme 'Futura'

still not work
but i try manual is work 

how i change it?
![image](https://github.com/user-attachments/assets/d2820412-2a58-41bb-8abc-0e332ab8d8ea)

**Comment by linkfrg** [comment]
Check ``~/.config/ignis/config.py``

**Comment by KnoyanMitsu** [comment]
> Check `~/.config/ignis/config.py`

ah edit from that
thanks bro
