### ISSUE TITLE
Black interface bug

### ISSUE THREAD

**Issue by HinaHyugaHime** [linkfrg/dotfiles#50]
when showing notifications it gives full black interface below the notification, and when opening apps launcher everything but the launcher is black

**Comment by HinaHyugaHime** [comment]
![image](https://github.com/user-attachments/assets/cc87d1c5-acc8-4a36-b012-67fbdd8dc84c)
![image](https://github.com/user-attachments/assets/68ac0b6c-1ced-4fda-b69c-dc3116f95496)
![image](https://github.com/user-attachments/assets/79438421-6953-4a81-8e94-bffd26c2fece)

**Comment by linkfrg** [comment]
Do you have modified ``~/.config/gtk-4.0/gtk.css``?

**Comment by HinaHyugaHime** [comment]
No?

**Comment by linkfrg** [comment]
Are you sure you haven't modified hyprland and ignis config?

**Comment by HinaHyugaHime** [comment]
Ive only changed background photo

**Comment by linkfrg** [comment]
> No?

This is a question? 
If you have any files in ``~/.config/gtk-4.0``, then remove them, they override style settings for Ignis and any other gtk4 app

**Comment by HinaHyugaHime** [comment]
> > No?
> 
> This is a question? If you have any files in `~/.config/gtk-4.0`, remove them, they override style settings for Ignis and any other gtk4 app

Will check

**Comment by HinaHyugaHime** [comment]
Yea fixed
