### ISSUE TITLE
[Question] How to Add Background Images to Launcher?

### ISSUE THREAD

**Issue by RoidedSasquatch** [linkfrg/dotfiles#52]
Hello, I am just wondering how I can add an image as the background of the launcher (behind the searchbar, .launcher in the scss)? I have been using these configs as a base and tweaking/modifying them to fit my needs but have not been able to figure this image issue out. I have tried the background-image and background properties in the .scss file, using URL(), and images are not rendered/rendered transparent. I also tried adding a Widget.Picture() to the Python file to see if I could get it to display that way, and had the same issue. I tried both absolute and relative paths to my image and sill no luck.

**Comment by linkfrg** [comment]
How do you set an image as the background in scss?
It should look like this:
```scss
background-image: url('file:///PATH/TO/FILE');
```

**Comment by RoidedSasquatch** [comment]
That worked, thank you! I had an error in my path. Marking this as completed!
