### ISSUE TITLE
Widget `reveal` cannot be show when updating variable `open_center_control`

### ISSUE THREAD

**Issue by elliot-zen** [linkfrg/dotfiles#7]
I copied you config file, but widget `control_center` is not working properly;

**Hyprland**
`Tag: v0.32.0-1-gc619e697`

**eww-tray-wayland**
`eww 0.4.0 a82ed62c25ba50f28dc8c3d57efe440d51d6136b`

https://github.com/linkfrg/dotfiles/assets/112766964/88665165-6162-4449-9313-ff258adf116f

Can you give me some help

**Comment by linkfrg** [comment]
follow step by step the installation guide in wiki and copy ALL config files. Otherwise do everything yourself
