### ISSUE TITLE
[Question] Some useful things that are missing from the config

### ISSUE THREAD

**Issue by Balssh** [linkfrg/dotfiles#8]
Hi there, again, stunning rice! I've been toying with it the past day and I feel like there are a couple of things that are missing for it to be perfect:
- lack of bluetooth control
- lack of brightness control
- eww widgets not closing when clicking outside them
- not being able to directly type into the launcher
I will look into implementing them myself, but I'm not not used to eww at all so I may fail. Anyway, thanks for your effort! <3

**Comment by linkfrg** [comment]
I don't have a laptop so i can't test brightness and Bluetooth control. I think clicking outside eww windows to close  them not such useful and can cause some problems with animation and lags. Regarding the launcher, idk how to do this in eww. Implement it by yourself if you wish
