### ISSUE TITLE
Please add old vertical bar files big fan 🥺🥺

### ISSUE THREAD

**Issue by vs66388** [linkfrg/dotfiles#9]
Please make a repo for your old vertical bar configs and battery icon to it too and 1 permission I might ask can I make a distro out of your configs

**Comment by linkfrg** [comment]
i don't have so much free time so i will not make a repo for vertical bar soon. Yes you can make a s distro from my configs, but keep in mind that they don't have bluetooth and brightness control and i am not going to implement them by myself
